### PR TITLE
Fixes to the Histogram class in order to properly compute the error

### PR DESCRIPTION
**Pull request by andrea-celentano**
Dear AmpTools authors,
since the introduction of 2D histograms that I implemented in AmpTools, I never checked about histogram errors. I made a minimal set of changes to the AmpTools software (Histogram class) in order to properly compute them. The fix is 100% retro-compatible, and the users don't have to change any single line of code in their application to have the new correct calculation working.
Andrea Celentano

### CODE REVIEW

**Comment by mashephe** [comment]
Andrea,
Which version were you working with as a starting point?  Can you start by checking out the master and then applying your changes on top of that?  It looks like some of your changes already exist in some classes.  Additionally, your change appears to reintroduce some things, like calls to clear(), that were removed because they were problematic.
Matt

**Comment by andrea-celentano** [comment]
Dear Matt, 
what I did is the following: I forked your repository, then I did a copy-paste of the files with modifications (the histogram files), then I asked for a pull request

Bests,
Andrea

**Comment by mashephe** [comment]
Andrea,

I think the functionality that you are trying to introduce already exists in the master branch.  I don't remember when it was introduced, but we could look at the history.  Notice that the diff for your pull request seems to be replacing one line with another of similar function in many places.

Also, when did your copy/paste, I'm afraid that you might plow over changes to the classes that happened beyond the version of those classes that you are using as a starting point.

Matt

**Comment by andrea-celentano** [comment]
Hi Matt,
I just open the histogram files in the new AmpTools version (that I never looked before), it looks that the way you implemented histogram errors is exactly the same as I did! 

I think you can just ignore my pull request..

Andrea

**Comment by mashephe** [comment]
Functionality already exists in the master.

**Pull request closed without merging**
